modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/7994406-stack/RandomEffectBlock/issues"

[[mods]]
modId="randomeffect"
version="1.0.0"
displayName="Random Effect Block"
authors="YTBudka_mx"
description="''"

[[dependencies.randomeffect]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.randomeffect]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
