modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="randomeffect"
version="1.0.0"
displayName="Random Effect Block"
authors="YTBudka_mx"
description="Gives random effects in 10 block radius"

[[dependencies.randomeffect]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.randomeffect]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1, 1.21)"
    ordering="NONE"
    side="BOTH"
