modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="randomeffect"
version="1.0.0"
displayName="Random Effect Block"
description="Block that gives random effects to players every 10 seconds"
authors="YourName"

[[dependencies.randomeffect]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.randomeffect]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
